"""add templet table

Revision ID: 47e91e3cfc80
Revises: ea52801539e1
Create Date: 2018-03-26 17:54:29.810591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47e91e3cfc80'
down_revision = 'ea52801539e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sn', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cover_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('use_times', sa.Integer(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sn')
    )
    op.create_index(op.f('ix_templets_user_id'), 'templets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templets_user_id'), table_name='templets')
    op.drop_table('templets')
    # ### end Alembic commands ###
