"""add type sensitive

Revision ID: 5ae43c0a7c70
Revises: 6980a9d5070a
Create Date: 2018-03-27 08:59:38.296120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae43c0a7c70'
down_revision = '6980a9d5070a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensitives', sa.Column('type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensitives', 'type')
    # ### end Alembic commands ###
