"""add sensitive table

Revision ID: 6980a9d5070a
Revises: e8981e85e6c0
Create Date: 2018-03-26 20:56:33.871502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6980a9d5070a'
down_revision = 'e8981e85e6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensitives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensitives')
    # ### end Alembic commands ###
