"""add asset directory table

Revision ID: e8981e85e6c0
Revises: 47e91e3cfc80
Create Date: 2018-03-26 18:53:50.044972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8981e85e6c0'
down_revision = '47e91e3cfc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('directory_id', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('mime', sa.String(length=64), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('top', sa.SmallInteger(), nullable=True),
    sa.Column('type', sa.SmallInteger(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_directories_name'), 'directories', ['name'], unique=False)
    op.add_column('imagesets', sa.Column('cover_id', sa.Integer(), nullable=True))
    op.add_column('imagesets', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_index('filepath', table_name='imagesets')
    op.drop_column('imagesets', 'height')
    op.drop_column('imagesets', 'width')
    op.drop_column('imagesets', 'filepath')
    op.drop_column('imagesets', 'size')
    op.drop_column('imagesets', 'mime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagesets', sa.Column('mime', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('imagesets', sa.Column('size', mysql.FLOAT(), nullable=True))
    op.add_column('imagesets', sa.Column('filepath', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('imagesets', sa.Column('width', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('imagesets', sa.Column('height', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('filepath', 'imagesets', ['filepath'], unique=True)
    op.drop_column('imagesets', 'name')
    op.drop_column('imagesets', 'cover_id')
    op.drop_index(op.f('ix_directories_name'), table_name='directories')
    op.drop_table('directories')
    op.drop_table('assets')
    # ### end Alembic commands ###
